### ISSUE TITLE
[value]% - quantity as percentage of total USDT balance

### ISSUE THREAD

**Issue by hebe061103** [germangar/whook#7]
How to set this parameter in the TV message, thank you!

**Comment by germangar** [comment]
Hey,
If you want to make a buy order for, let's say, the 25% of your balance you simply put 25% (instead of 25$) as value in the alert message.

But this is if you are generating the messages yourself (using the alert function). If the strategy is working in percentages (defined in the strategy settings) you don't have to do anything. The strategy will already convert the percentage to the final number. Strategies send their orders in the base currency (the coin you're trading).
